services:
  graph-node:
    image: graphprotocol/graph-node
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
    depends_on:
      - ipfs
      - postgres
    environment:
      postgres_host: postgres
      postgres_user: ${POSTGRES_USER}
      postgres_pass: ${POSTGRES_PASSWORD}
      postgres_db: ${POSTGRES_DB}
      ipfs: 'ipfs:5001'
      ethereum: '${ETHEREUM_RPC_URL}'
      GRAPH_LOG: info

  ipfs:
    image: ipfs/go-ipfs:v0.10.0
    ports:
      - '5001:5001'

  postgres:
    image: postgres
    ports:
      - '5432:5432'
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  postgres:
  ipfs:
